### PR TITLE
Reliability & Efficiency Changes

### PR DESCRIPTION
**Pull request by SANdood**
Background: Some Zigbee Dimmers (on both Hubitat and SmartThings) will report level changes AFTER the switch is turned off - this will cause extraneous setLevel() commands to be sent to the Slave devices, which will turn the Slave lights back on immediately after they are turned off.

Changes include:
- Allow one device to be designated the master (optional). If set, ONLY changes to this device will be reflected
- Added a separate option to poll the Master device every 5 minutes (not really needed in most cases, as you know).
- Ignore any level changes that occur on the Master when it is turned off
- Eliminate try/catch; instead check whether the device has the desired setLevel() or setSpeed()  commands before trying to invoke the command
- Don't send a setLevel/setSpeed command if the target device is already at the desired level/speed (I probably should have done on/off also).

Note that my code uses the Hubitat-specific form of device.currentValue('attribute', true), which forces the device to return the latest value (which may or may not be the same as the devices' currently cached value). This gives better reliability when multiple events are logged to a device at the same time, as in switch.off/power/level reports that happen within milliseconds on Zigbee dimmers.

### CODE REVIEW

**Review by joelwetzel — CHANGES_REQUESTED** [review]
Thanks for the pull request!  So, I like most of your changes, but the implementation of the master device will need to change.  It breaks one of my primary use cases.  I think we're having different interpretations of what master means.  It looks like in your case, master means "only do one-way syncing from the master to the slave devices."  In my case, I used master to mean "still do two-way syncing, but periodically check the master and make sure the slaves are in the same state."

Let me give my use case:  I have a smartplug that has a lamp plugged into it.  I also have a scene controller on my wall with a lighted toggle button (that is exposed to Hubitat as a virtual switch.)  I use Switch Bindings to bind the Scene Controller button to the lamp's smartplug.  This way I can control my lamp using the wall button.  I set the smartplug as the master, so that if the scene controller ever gets out of sync, it will re-sync to whatever state the lamp is truly in.  However, I still need two-way binding, because sometimes I use Alexa to turn off the lamp, or use another automation to turn off the lamp.  And I want the scene controller to update it's little indicator light to match what the lamp is now doing.

So I think we need to split it into three config items:
1 - Designate which switch is the master
2 - If a master has been set, do we want polling and re-syncing or not?
3 - If a master has been set, do we still do two-way binding?  Or are we only doing one-way binding?

**Comment by SANdood** [comment]
Sounds fine to me:
If you select a master device, it would enable 2 config questions
- master/slave or any-to-all (peer to peer)?
- poll/resync master to the others (yes/no)?

Let me know if you need my help in updating the code to handle the above. 

PS- the Hubitat folks confirmed they will be fixing the driver that causes the issue that led me to this in the first place. 

Thanks!
      Barry

**Comment by joelwetzel** [comment]
Oh, I would love help!  I wouldn't be able to get to it for a while, but I'll gladly accept help.  :)

**Comment by SANdood** [comment]
Updated version on the way

**Pull request closed without merging**
